/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.Conectar;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Kemu27
 */
public class Tela_Loguin extends javax.swing.JFrame {

      /**
     * Creates new form Tela_Principal
     */
    public Tela_Loguin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelícone = new javax.swing.JLabel();
        jButtonentrar1 = new javax.swing.JButton();
        jButtonentrar = new javax.swing.JButton();
        jButtonsair = new javax.swing.JButton();
        jTextFieldnomeuser = new javax.swing.JTextField();
        jPasswordFieldsenha = new javax.swing.JPasswordField();
        jLabelusuário = new javax.swing.JLabel();
        jLabelsenha = new javax.swing.JLabel();
        jLabelTransparencia = new javax.swing.JLabel();
        Fundo_Tela_Loguin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelícone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/pessoa.png"))); // NOI18N
        getContentPane().add(jLabelícone);
        jLabelícone.setBounds(450, 200, 50, 50);

        jButtonentrar1.setText("Cancelar");
        jButtonentrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonentrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonentrar1);
        jButtonentrar1.setBounds(500, 380, 90, 30);

        jButtonentrar.setText("Entrar");
        jButtonentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonentrarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonentrar);
        jButtonentrar.setBounds(380, 380, 90, 30);

        jButtonsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/sair.png"))); // NOI18N
        jButtonsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsairActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonsair);
        jButtonsair.setBounds(0, 0, 30, 30);
        getContentPane().add(jTextFieldnomeuser);
        jTextFieldnomeuser.setBounds(380, 280, 210, 30);
        getContentPane().add(jPasswordFieldsenha);
        jPasswordFieldsenha.setBounds(380, 330, 210, 30);

        jLabelusuário.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/login.png"))); // NOI18N
        getContentPane().add(jLabelusuário);
        jLabelusuário.setBounds(350, 270, 40, 50);

        jLabelsenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/senha.png"))); // NOI18N
        getContentPane().add(jLabelsenha);
        jLabelsenha.setBounds(350, 320, 40, 50);

        jLabelTransparencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/trasnparencia.png"))); // NOI18N
        getContentPane().add(jLabelTransparencia);
        jLabelTransparencia.setBounds(330, 200, 290, 250);

        Fundo_Tela_Loguin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/fundo.png"))); // NOI18N
        getContentPane().add(Fundo_Tela_Loguin);
        Fundo_Tela_Loguin.setBounds(0, 0, 710, 480);

        setSize(new java.awt.Dimension(719, 509));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonentrarActionPerformed
           
        if (jTextFieldnomeuser.getText().equals("admin") && jPasswordFieldsenha.getText().equals("admin")) {
            Tela_Principal tela = new Tela_Principal();
            tela.setVisible(true);
            dispose();
            
        } else {
                    JOptionPane.showMessageDialog(rootPane,"Senha ou Usuários Inválidos");
        }                                 
    }//GEN-LAST:event_jButtonentrarActionPerformed

    private void jButtonentrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonentrar1ActionPerformed
      jTextFieldnomeuser.setText(null);
      jPasswordFieldsenha.setText(null);
    }//GEN-LAST:event_jButtonentrar1ActionPerformed

    private void jButtonsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsairActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jButtonsairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Loguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Loguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Loguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Loguin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Loguin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fundo_Tela_Loguin;
    private javax.swing.JButton jButtonentrar;
    private javax.swing.JButton jButtonentrar1;
    private javax.swing.JButton jButtonsair;
    private javax.swing.JLabel jLabelTransparencia;
    private javax.swing.JLabel jLabelsenha;
    private javax.swing.JLabel jLabelusuário;
    private javax.swing.JLabel jLabelícone;
    private javax.swing.JPasswordField jPasswordFieldsenha;
    private javax.swing.JTextField jTextFieldnomeuser;
    // End of variables declaration//GEN-END:variables
}
