/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kemu27
 */
public class Tela_Principal extends javax.swing.JFrame {

    dao.Conectar conecta = new dao.Conectar();

    public Tela_Principal() {
        initComponents();
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JInternalFrameMenu = new javax.swing.JInternalFrame();
        Painel_InternalFrame_Menu = new javax.swing.JPanel();
        JButtonUsuario = new javax.swing.JButton();
        JButtonCliente = new javax.swing.JButton();
        JButtonAnimal = new javax.swing.JButton();
        JButtonProduto = new javax.swing.JButton();
        JButtonRelatorio = new javax.swing.JButton();
        JButtonAgendamento = new javax.swing.JButton();
        jLabelproduto = new javax.swing.JLabel();
        jLabelrelatório = new javax.swing.JLabel();
        jButtonCalculadora = new javax.swing.JButton();
        Sair_Botão_InternalFrame = new javax.swing.JButton();
        jLabelcalculadora = new javax.swing.JLabel();
        jLabelusuário = new javax.swing.JLabel();
        jLabelanimal1 = new javax.swing.JLabel();
        jLabelcadastro1 = new javax.swing.JLabel();
        jLabelcliente2 = new javax.swing.JLabel();
        jLabelrelatório1 = new javax.swing.JLabel();
        jLabelagenda1 = new javax.swing.JLabel();
        jLabelrela1 = new javax.swing.JLabel();
        jLabelfundomeu = new javax.swing.JLabel();
        jLabelImgFundo = new javax.swing.JLabel();
        Barra_Menu = new javax.swing.JMenuBar();
        JMenuCadastros = new javax.swing.JMenu();
        JMenuItemUsuarios = new javax.swing.JMenuItem();
        JMenuItemCliente = new javax.swing.JMenuItem();
        JMenuItemProdutos = new javax.swing.JMenuItem();
        Cad_Produto_Menu = new javax.swing.JMenuItem();
        JMenuAdendamentos = new javax.swing.JMenu();
        jMenuItemAgendamento = new javax.swing.JMenuItem();
        JMenuRelatorio = new javax.swing.JMenu();
        JMenuCalculadora = new javax.swing.JMenu();
        jMenuItemCalculadora = new javax.swing.JMenuItem();
        JMenuItemMenu = new javax.swing.JMenu();
        Menu_Ferramentas_Menu = new javax.swing.JMenuItem();
        JMenuSair = new javax.swing.JMenu();
        JMenuItemSairSistema = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JInternalFrameMenu.setTitle("Menu");
        JInternalFrameMenu.setToolTipText("");
        JInternalFrameMenu.setVisible(true);
        JInternalFrameMenu.getContentPane().setLayout(null);

        Painel_InternalFrame_Menu.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Painel_InternalFrame_Menu.setLayout(null);

        JButtonUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/Cadastro-Usuário.png"))); // NOI18N
        JButtonUsuario.setToolTipText("Usuário");
        JButtonUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonUsuarioActionPerformed(evt);
            }
        });
        Painel_InternalFrame_Menu.add(JButtonUsuario);
        JButtonUsuario.setBounds(10, 160, 120, 120);

        JButtonCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/cliente.png"))); // NOI18N
        JButtonCliente.setToolTipText("Cliente");
        JButtonCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonClienteActionPerformed(evt);
            }
        });
        Painel_InternalFrame_Menu.add(JButtonCliente);
        JButtonCliente.setBounds(160, 160, 120, 120);

        JButtonAnimal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/animal.png"))); // NOI18N
        JButtonAnimal.setToolTipText("Animal");
        JButtonAnimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAnimalActionPerformed(evt);
            }
        });
        Painel_InternalFrame_Menu.add(JButtonAnimal);
        JButtonAnimal.setBounds(10, 330, 120, 120);

        JButtonProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/produto.png"))); // NOI18N
        JButtonProduto.setToolTipText("Produto");
        JButtonProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonProdutoActionPerformed(evt);
            }
        });
        Painel_InternalFrame_Menu.add(JButtonProduto);
        JButtonProduto.setBounds(160, 330, 120, 120);

        JButtonRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/1.png"))); // NOI18N
        JButtonRelatorio.setToolTipText("Relatórios");
        Painel_InternalFrame_Menu.add(JButtonRelatorio);
        JButtonRelatorio.setBounds(450, 230, 120, 120);

        JButtonAgendamento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/ésse.png"))); // NOI18N
        JButtonAgendamento.setToolTipText("Agendamentos");
        JButtonAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAgendamentoActionPerformed(evt);
            }
        });
        Painel_InternalFrame_Menu.add(JButtonAgendamento);
        JButtonAgendamento.setBounds(750, 170, 120, 120);

        jLabelproduto.setFont(new java.awt.Font("Segoe UI Historic", 2, 18)); // NOI18N
        jLabelproduto.setText("Produto");
        Painel_InternalFrame_Menu.add(jLabelproduto);
        jLabelproduto.setBounds(190, 290, 90, 50);

        jLabelrelatório.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/relatórios.png"))); // NOI18N
        Painel_InternalFrame_Menu.add(jLabelrelatório);
        jLabelrelatório.setBounds(760, 20, 236, 80);

        jButtonCalculadora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/2.png"))); // NOI18N
        jButtonCalculadora.setToolTipText("Calculadora");
        jButtonCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculadoraActionPerformed(evt);
            }
        });
        Painel_InternalFrame_Menu.add(jButtonCalculadora);
        jButtonCalculadora.setBounds(910, 170, 120, 120);

        Sair_Botão_InternalFrame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/sair.png"))); // NOI18N
        Sair_Botão_InternalFrame.setToolTipText("Sair do Sistema");
        Sair_Botão_InternalFrame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair_Botão_InternalFrameActionPerformed(evt);
            }
        });
        Painel_InternalFrame_Menu.add(Sair_Botão_InternalFrame);
        Sair_Botão_InternalFrame.setBounds(990, 430, 40, 30);

        jLabelcalculadora.setFont(new java.awt.Font("Segoe UI Historic", 2, 18)); // NOI18N
        jLabelcalculadora.setText("Calculadora");
        Painel_InternalFrame_Menu.add(jLabelcalculadora);
        jLabelcalculadora.setBounds(920, 130, 110, 50);

        jLabelusuário.setFont(new java.awt.Font("Segoe UI Historic", 2, 18)); // NOI18N
        jLabelusuário.setText("Usuário");
        Painel_InternalFrame_Menu.add(jLabelusuário);
        jLabelusuário.setBounds(40, 120, 90, 50);

        jLabelanimal1.setFont(new java.awt.Font("Segoe UI Historic", 2, 18)); // NOI18N
        jLabelanimal1.setText("Animal");
        Painel_InternalFrame_Menu.add(jLabelanimal1);
        jLabelanimal1.setBounds(40, 290, 90, 50);

        jLabelcadastro1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/cadastro.png"))); // NOI18N
        Painel_InternalFrame_Menu.add(jLabelcadastro1);
        jLabelcadastro1.setBounds(40, 20, 236, 80);

        jLabelcliente2.setFont(new java.awt.Font("Segoe UI Historic", 2, 18)); // NOI18N
        jLabelcliente2.setText("Cliente");
        Painel_InternalFrame_Menu.add(jLabelcliente2);
        jLabelcliente2.setBounds(190, 120, 90, 50);

        jLabelrelatório1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/relatórios.png"))); // NOI18N
        Painel_InternalFrame_Menu.add(jLabelrelatório1);
        jLabelrelatório1.setBounds(400, 20, 236, 80);

        jLabelagenda1.setFont(new java.awt.Font("Segoe UI Historic", 2, 18)); // NOI18N
        jLabelagenda1.setText("Agenda");
        Painel_InternalFrame_Menu.add(jLabelagenda1);
        jLabelagenda1.setBounds(770, 130, 90, 50);

        jLabelrela1.setFont(new java.awt.Font("Segoe UI Historic", 2, 18)); // NOI18N
        jLabelrela1.setText("Relatório");
        Painel_InternalFrame_Menu.add(jLabelrela1);
        jLabelrela1.setBounds(470, 190, 90, 50);

        jLabelfundomeu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/asdfa.png"))); // NOI18N
        jLabelfundomeu.setText("jLabel1");
        Painel_InternalFrame_Menu.add(jLabelfundomeu);
        jLabelfundomeu.setBounds(-180, -260, 1600, 1310);

        JInternalFrameMenu.getContentPane().add(Painel_InternalFrame_Menu);
        Painel_InternalFrame_Menu.setBounds(0, 0, 1050, 480);

        getContentPane().add(JInternalFrameMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 1068, 516));

        jLabelImgFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/dog.png"))); // NOI18N
        getContentPane().add(jLabelImgFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-990, -60, 2900, 1290));

        JMenuCadastros.setText("Cadastros");

        JMenuItemUsuarios.setText("Usuários");
        JMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemUsuariosActionPerformed(evt);
            }
        });
        JMenuCadastros.add(JMenuItemUsuarios);

        JMenuItemCliente.setText("Cliente");
        JMenuItemCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemClienteActionPerformed(evt);
            }
        });
        JMenuCadastros.add(JMenuItemCliente);

        JMenuItemProdutos.setText("Animal");
        JMenuItemProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemProdutosActionPerformed(evt);
            }
        });
        JMenuCadastros.add(JMenuItemProdutos);

        Cad_Produto_Menu.setText("Produtos");
        Cad_Produto_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cad_Produto_MenuActionPerformed(evt);
            }
        });
        JMenuCadastros.add(Cad_Produto_Menu);

        Barra_Menu.add(JMenuCadastros);

        JMenuAdendamentos.setText("Agendamentos");

        jMenuItemAgendamento.setText("Agendar");
        jMenuItemAgendamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAgendamentoActionPerformed(evt);
            }
        });
        JMenuAdendamentos.add(jMenuItemAgendamento);

        Barra_Menu.add(JMenuAdendamentos);

        JMenuRelatorio.setText("Relatório");
        Barra_Menu.add(JMenuRelatorio);

        JMenuCalculadora.setText("Calculadora");

        jMenuItemCalculadora.setText("Calculadora");
        jMenuItemCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCalculadoraActionPerformed(evt);
            }
        });
        JMenuCalculadora.add(jMenuItemCalculadora);

        Barra_Menu.add(JMenuCalculadora);

        JMenuItemMenu.setText("Ferramentas");

        Menu_Ferramentas_Menu.setText("Menu");
        Menu_Ferramentas_Menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu_Ferramentas_MenuActionPerformed(evt);
            }
        });
        JMenuItemMenu.add(Menu_Ferramentas_Menu);

        Barra_Menu.add(JMenuItemMenu);

        JMenuSair.setText("Sair");

        JMenuItemSairSistema.setText("Sair do Sistema");
        JMenuItemSairSistema.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMenuItemSairSistemaActionPerformed(evt);
            }
        });
        JMenuSair.add(JMenuItemSairSistema);

        Barra_Menu.add(JMenuSair);

        setJMenuBar(Barra_Menu);

        setSize(new java.awt.Dimension(1134, 649));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemUsuariosActionPerformed
        Tela_Cad_Usuario tela_user = new Tela_Cad_Usuario();
        tela_user.setVisible(true);
    }//GEN-LAST:event_JMenuItemUsuariosActionPerformed

    private void Sair_Botão_InternalFrameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair_Botão_InternalFrameActionPerformed
        JInternalFrameMenu.dispose();
        // TODO add yourjB handling code here:
    }//GEN-LAST:event_Sair_Botão_InternalFrameActionPerformed

    private void Menu_Ferramentas_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu_Ferramentas_MenuActionPerformed

        Tela_Principal tela_pri = new Tela_Principal();
        tela_pri.setVisible(true);
        // Chamadando Tela de Menus, através do botão ferramentas
    }//GEN-LAST:event_Menu_Ferramentas_MenuActionPerformed

    private void JMenuItemSairSistemaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemSairSistemaActionPerformed
        System.exit(0);
        conecta.desconectar();

// Sair do sistema barra de Menu
    }//GEN-LAST:event_JMenuItemSairSistemaActionPerformed

    private void JButtonUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonUsuarioActionPerformed

        Tela_Cad_Usuario tela_user = new Tela_Cad_Usuario();
        tela_user.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_JButtonUsuarioActionPerformed

    private void JButtonAnimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAnimalActionPerformed
        Tela_Cad_Animal tela_animal = new Tela_Cad_Animal();
        tela_animal.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_JButtonAnimalActionPerformed

    private void JMenuItemProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemProdutosActionPerformed
        Tela_Cad_Animal tela_animal = new Tela_Cad_Animal();
        tela_animal.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_JMenuItemProdutosActionPerformed

    private void JButtonClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonClienteActionPerformed
        Tela_Cada_Cliente tela_cliente = new Tela_Cada_Cliente();
        tela_cliente.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_JButtonClienteActionPerformed

    private void JMenuItemClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMenuItemClienteActionPerformed
        Tela_Cada_Cliente tela_cliente = new Tela_Cada_Cliente();
        tela_cliente.setVisible(true);
    }//GEN-LAST:event_JMenuItemClienteActionPerformed

    private void jMenuItemCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCalculadoraActionPerformed

        try {
            Runtime.getRuntime().exec("cmd.exe /C start calc.exe");
// TODO add your handling code here:
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_jMenuItemCalculadoraActionPerformed

    private void JButtonProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonProdutoActionPerformed
        Tela_Cad_Produto tel_pro = new Tela_Cad_Produto();
        tel_pro.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_JButtonProdutoActionPerformed

    private void Cad_Produto_MenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cad_Produto_MenuActionPerformed
        Tela_Cad_Produto tel_pro = new Tela_Cad_Produto();
        tel_pro.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_Cad_Produto_MenuActionPerformed

    private void jMenuItemAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAgendamentoActionPerformed
        Tela_Agendamento tel_agen = new Tela_Agendamento();
        tel_agen.setVisible(true);

// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemAgendamentoActionPerformed

    private void jButtonCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculadoraActionPerformed

        try {
            Runtime.getRuntime().exec("cmd.exe /C start calc.exe");
// TODO add your handling code here:
        } catch (IOException ex) {
            ex.printStackTrace();
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCalculadoraActionPerformed

    private void JButtonAgendamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAgendamentoActionPerformed
        Tela_Agendamento tel_agen = new Tela_Agendamento();
        tel_agen.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonAgendamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Barra_Menu;
    private javax.swing.JMenuItem Cad_Produto_Menu;
    private javax.swing.JButton JButtonAgendamento;
    private javax.swing.JButton JButtonAnimal;
    private javax.swing.JButton JButtonCliente;
    private javax.swing.JButton JButtonProduto;
    private javax.swing.JButton JButtonRelatorio;
    private javax.swing.JButton JButtonUsuario;
    private javax.swing.JInternalFrame JInternalFrameMenu;
    private javax.swing.JMenu JMenuAdendamentos;
    private javax.swing.JMenu JMenuCadastros;
    private javax.swing.JMenu JMenuCalculadora;
    private javax.swing.JMenuItem JMenuItemCliente;
    private javax.swing.JMenu JMenuItemMenu;
    private javax.swing.JMenuItem JMenuItemProdutos;
    private javax.swing.JMenuItem JMenuItemSairSistema;
    private javax.swing.JMenuItem JMenuItemUsuarios;
    private javax.swing.JMenu JMenuRelatorio;
    private javax.swing.JMenu JMenuSair;
    private javax.swing.JMenuItem Menu_Ferramentas_Menu;
    private javax.swing.JPanel Painel_InternalFrame_Menu;
    private javax.swing.JButton Sair_Botão_InternalFrame;
    private javax.swing.JButton jButtonCalculadora;
    private javax.swing.JLabel jLabelImgFundo;
    private javax.swing.JLabel jLabelagenda1;
    private javax.swing.JLabel jLabelanimal1;
    private javax.swing.JLabel jLabelcadastro1;
    private javax.swing.JLabel jLabelcalculadora;
    private javax.swing.JLabel jLabelcliente2;
    private javax.swing.JLabel jLabelfundomeu;
    private javax.swing.JLabel jLabelproduto;
    private javax.swing.JLabel jLabelrela1;
    private javax.swing.JLabel jLabelrelatório;
    private javax.swing.JLabel jLabelrelatório1;
    private javax.swing.JLabel jLabelusuário;
    private javax.swing.JMenuItem jMenuItemAgendamento;
    private javax.swing.JMenuItem jMenuItemCalculadora;
    // End of variables declaration//GEN-END:variables
}
