/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.AnimalDao;
import dao.ClienteDao;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import model.Animal;
import model.Cliente;

/**
 *
 * @author S.I
 */
public class Tela_Cada_Cliente extends javax.swing.JFrame {

    Cliente mod = new Cliente();
    ClienteDao cadastro = new ClienteDao();
    dao.Conectar conectar = new dao.Conectar();

    int flag = 0;

    public Tela_Cada_Cliente() {
        conectar.conexao();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlabelCliente = new javax.swing.JLabel();
        Painel_Tela_Cad_Cliente = new javax.swing.JPanel();
        Nome_Tela_Cad_Usuario = new javax.swing.JLabel();
        JComboBoxEstado = new javax.swing.JComboBox();
        JTexFieldPesquisar = new javax.swing.JTextField();
        JButtonNovo = new javax.swing.JButton();
        JButtonSalvar = new javax.swing.JButton();
        JButtonAlterar = new javax.swing.JButton();
        JButtonCancelar = new javax.swing.JButton();
        jLabelCpf = new javax.swing.JLabel();
        jLabelRg = new javax.swing.JLabel();
        jLabelData = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jLabelLogradouro = new javax.swing.JLabel();
        jLabelComplemento = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jLabelCep = new javax.swing.JLabel();
        jLabeContato = new javax.swing.JLabel();
        jLabelCartao = new javax.swing.JLabel();
        jLabelValidade = new javax.swing.JLabel();
        jLabelNCartao = new javax.swing.JLabel();
        jLabelIdAnimal = new javax.swing.JLabel();
        jTextFieldComplemento = new javax.swing.JTextField();
        jTextFieldCartao = new javax.swing.JTextField();
        jTextFieldNCartao = new javax.swing.JTextField();
        jFormattedTextFieldCpf = new javax.swing.JFormattedTextField();
        jFormattedTextFieldRg = new javax.swing.JFormattedTextField();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldIdAnimal = new javax.swing.JTextField();
        JComboBoxSexo = new javax.swing.JComboBox();
        jFormattedTextFieldCep = new javax.swing.JFormattedTextField();
        jFormattedTextFieldContato = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jFormattedTextFieldValidade = new javax.swing.JFormattedTextField();
        jFormattedTextFieldData = new javax.swing.JFormattedTextField();
        jTextFieldLogradouro = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jTextFieldemail = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabelfundo = new javax.swing.JLabel();
        jLabelfundotitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JlabelCliente.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        JlabelCliente.setForeground(new java.awt.Color(255, 255, 255));
        JlabelCliente.setText("Cadastro de Cliente");
        getContentPane().add(JlabelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        Painel_Tela_Cad_Cliente.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Painel_Tela_Cad_Cliente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Nome_Tela_Cad_Usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nome_Tela_Cad_Usuario.setText("Nome");
        Painel_Tela_Cad_Cliente.add(Nome_Tela_Cad_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        JComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " AC", " AL", " AP", " AM", " BA", " CE", " DF", " ES", " GO", " MA", " MT", " MS", " MG", " PA", " PB", " PR", " PE", " PI", " RJ", " RN", " RS", " RO", " RR", " SC", " SP", " SE", " TO" }));
        Painel_Tela_Cad_Cliente.add(JComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 220, 50, 31));
        Painel_Tela_Cad_Cliente.add(JTexFieldPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 400, 350, 31));

        JButtonNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JButtonNovo.setText("Novo");
        JButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonNovoActionPerformed(evt);
            }
        });
        Painel_Tela_Cad_Cliente.add(JButtonNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 84, 33));

        JButtonSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JButtonSalvar.setText("Salvar");
        JButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSalvarActionPerformed(evt);
            }
        });
        Painel_Tela_Cad_Cliente.add(JButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 84, 33));

        JButtonAlterar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JButtonAlterar.setText("Alterar");
        JButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAlterarActionPerformed(evt);
            }
        });
        Painel_Tela_Cad_Cliente.add(JButtonAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 84, 35));

        JButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JButtonCancelar.setText("Cancelar");
        JButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonCancelarActionPerformed(evt);
            }
        });
        Painel_Tela_Cad_Cliente.add(JButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 84, 35));

        jLabelCpf.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCpf.setText("Cpf");
        Painel_Tela_Cad_Cliente.add(jLabelCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, -1, -1));

        jLabelRg.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelRg.setText("Rg");
        Painel_Tela_Cad_Cliente.add(jLabelRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jLabelData.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelData.setText("Data de Nascimento");
        Painel_Tela_Cad_Cliente.add(jLabelData, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        jLabelSexo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSexo.setText("Sexo");
        Painel_Tela_Cad_Cliente.add(jLabelSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 110, -1, -1));

        jLabelLogradouro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelLogradouro.setText("Logradouro");
        Painel_Tela_Cad_Cliente.add(jLabelLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, -1, -1));

        jLabelComplemento.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelComplemento.setText("Complemento");
        Painel_Tela_Cad_Cliente.add(jLabelComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, -1));

        jLabelNumero.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumero.setText("Nº");
        Painel_Tela_Cad_Cliente.add(jLabelNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 220, -1, -1));

        jLabelCidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCidade.setText("Cidade");
        Painel_Tela_Cad_Cliente.add(jLabelCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 170, -1, -1));

        jLabelEmail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEmail.setText("E-mail");
        Painel_Tela_Cad_Cliente.add(jLabelEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 270, -1, -1));

        jLabelEstado.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelEstado.setText("Estado");
        Painel_Tela_Cad_Cliente.add(jLabelEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, -1, -1));

        jLabelCep.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCep.setText("Cep");
        Painel_Tela_Cad_Cliente.add(jLabelCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 220, 40, -1));

        jLabeContato.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabeContato.setText("Contato");
        Painel_Tela_Cad_Cliente.add(jLabeContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, -1, -1));

        jLabelCartao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelCartao.setText("Cartão de Crédito");
        Painel_Tela_Cad_Cliente.add(jLabelCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 270, -1, -1));

        jLabelValidade.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelValidade.setText("Validade");
        Painel_Tela_Cad_Cliente.add(jLabelValidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, -1, 20));

        jLabelNCartao.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNCartao.setText("Nº do Cartão");
        Painel_Tela_Cad_Cliente.add(jLabelNCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 110, -1));

        jLabelIdAnimal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelIdAnimal.setText("Id_Animal");
        Painel_Tela_Cad_Cliente.add(jLabelIdAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 60, -1, -1));
        Painel_Tela_Cad_Cliente.add(jTextFieldComplemento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 210, 30));
        Painel_Tela_Cad_Cliente.add(jTextFieldCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 270, 180, 30));
        Painel_Tela_Cad_Cliente.add(jTextFieldNCartao, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 190, 30));

        try {
            jFormattedTextFieldCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Painel_Tela_Cad_Cliente.add(jFormattedTextFieldCpf, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 110, 150, 30));

        try {
            jFormattedTextFieldRg.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Painel_Tela_Cad_Cliente.add(jFormattedTextFieldRg, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 130, 30));
        Painel_Tela_Cad_Cliente.add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 490, 30));
        Painel_Tela_Cad_Cliente.add(jTextFieldIdAnimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, 120, 30));

        JComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "M", "F" }));
        Painel_Tela_Cad_Cliente.add(JComboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 110, 50, 31));

        try {
            jFormattedTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Painel_Tela_Cad_Cliente.add(jFormattedTextFieldCep, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 160, 30));

        try {
            jFormattedTextFieldContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#- ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Painel_Tela_Cad_Cliente.add(jFormattedTextFieldContato, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 170, 30));

        jLabel1.setText("Cpf");
        Painel_Tela_Cad_Cliente.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, -1, -1));

        try {
            jFormattedTextFieldValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Painel_Tela_Cad_Cliente.add(jFormattedTextFieldValidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 320, 120, 30));

        try {
            jFormattedTextFieldData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        Painel_Tela_Cad_Cliente.add(jFormattedTextFieldData, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 120, 30));
        Painel_Tela_Cad_Cliente.add(jTextFieldLogradouro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 430, 30));
        Painel_Tela_Cad_Cliente.add(jTextFieldCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 190, 30));
        Painel_Tela_Cad_Cliente.add(jTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 120, 30));

        jTextFieldemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldemailActionPerformed(evt);
            }
        });
        Painel_Tela_Cad_Cliente.add(jTextFieldemail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 180, 30));

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        Painel_Tela_Cad_Cliente.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 400, 80, 30));

        jLabelfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/user.jpg"))); // NOI18N
        jLabelfundo.setText("jLabel1");
        Painel_Tela_Cad_Cliente.add(jLabelfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 950, 450));

        getContentPane().add(Painel_Tela_Cad_Cliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 970, 470));

        jLabelfundotitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/azul.jpg"))); // NOI18N
        getContentPane().add(jLabelfundotitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 60));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonNovoActionPerformed

        jFormattedTextFieldCep.setEnabled(true);
        jFormattedTextFieldContato.setEnabled(true);
        jFormattedTextFieldCpf.setEnabled(true);
        jFormattedTextFieldData.setEnabled(true);
        jFormattedTextFieldRg.setEnabled(true);
        jFormattedTextFieldValidade.setEnabled(true);
        JTexFieldPesquisar.setEnabled(true);
        jTextFieldCartao.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        jTextFieldComplemento.setEnabled(true);
        jTextFieldIdAnimal.setEnabled(true);
        jTextFieldLogradouro.setEnabled(true);
        jTextFieldNCartao.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldNumero.setEnabled(true);
        jTextFieldemail.setEnabled(true);
        LimparCampos();

        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonNovoActionPerformed
    private void LimparCampos() {
        jTextFieldNome.setText("");
        jFormattedTextFieldCpf.setText("");
        jFormattedTextFieldRg.setText("");
        jFormattedTextFieldData.setText("");
        jFormattedTextFieldValidade.setText("");
        jTextFieldLogradouro.setText("");
        jTextFieldComplemento.setText("");
        jTextFieldNumero.setText("");
        jTextFieldCidade.setText("");
        jFormattedTextFieldCep.setText("");
        jFormattedTextFieldContato.setText("");
        jTextFieldemail.setText("");
        jTextFieldCartao.setText("");
        jTextFieldNCartao.setText("");
        jTextFieldIdAnimal.setText("");
        JTexFieldPesquisar.setText("");
    }
    private void JButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSalvarActionPerformed

        SimpleDateFormat d = new SimpleDateFormat("dd/MM/yyyy");

        mod.setNome(jTextFieldNome.getText());
        mod.setCpf(jFormattedTextFieldCpf.getText());
        mod.setRg(jFormattedTextFieldRg.getText());
        mod.setData(jFormattedTextFieldData.getText());
        mod.setSexo((String) JComboBoxSexo.getSelectedItem());
        mod.setLogradouro(jTextFieldLogradouro.getText());
        mod.setComplemento(jTextFieldComplemento.getText());
        mod.setNumero(Integer.parseInt(jTextFieldNumero.getText()));
        mod.setCidade(jTextFieldCidade.getText());
        mod.setEstado((String) JComboBoxEstado.getSelectedItem());
        mod.setCep(jFormattedTextFieldCep.getText());
        mod.setContato(jFormattedTextFieldContato.getText());
        mod.setEmail(jTextFieldemail.getText());
        mod.setCartao(jTextFieldCartao.getText());
        mod.setValidade(jFormattedTextFieldValidade.getText());
        mod.setN_cartao(Integer.parseInt(jTextFieldNCartao.getText()));
        mod.setId_animal(Integer.parseInt(jTextFieldIdAnimal.getText()));

        cadastro.Salvar(mod);
        LimparCampos();
    }//GEN-LAST:event_JButtonSalvarActionPerformed

    private void JButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAlterarActionPerformed

        jTextFieldNome.setEnabled(true);
        jFormattedTextFieldCpf.setEnabled(true);
        jFormattedTextFieldRg.setEnabled(true);
        jFormattedTextFieldData.setEnabled(true);
        JComboBoxSexo.setEnabled(true);
        jTextFieldLogradouro.setEnabled(true);
        jTextFieldComplemento.setEnabled(true);
        jTextFieldNumero.setEnabled(true);
        jTextFieldCidade.setEnabled(true);
        JComboBoxEstado.setEnabled(true);
        jFormattedTextFieldCep.setEnabled(true);
        jFormattedTextFieldContato.setEnabled(true);
        jTextFieldemail.setEnabled(true);
        jTextFieldCartao.setEnabled(true);
        jFormattedTextFieldValidade.setEnabled(true);
        jTextFieldNCartao.setEnabled(true);
        jTextFieldIdAnimal.setEnabled(true);
     
        ClienteDao adao = new ClienteDao();
        Cliente a = new Cliente();
                    
        String nome = jTextFieldNome.getText();
        String cpf = jFormattedTextFieldCpf.getText();
        String rg = jFormattedTextFieldRg.getText();
        String data = jFormattedTextFieldData.getText();
        String item = (String) JComboBoxSexo.getSelectedItem();
        String logradouro = jTextFieldLogradouro.getText();
        String complemento = jTextFieldComplemento.getText();
        String numero = jTextFieldNumero.getText();
        String cidade = jTextFieldCidade.getText();
        String estado = (String) JComboBoxEstado.getSelectedItem();
        String cep = jFormattedTextFieldCep.getText();
        String contato = jFormattedTextFieldContato.getText();
        String email = jTextFieldemail.getText();
        String cartao = jTextFieldCartao.getText();
        String validade = jFormattedTextFieldValidade.getText();
        String ncartao = jTextFieldNCartao.getText();
        String idaniamal = jTextFieldIdAnimal.getText();
        
        a.setBandeira(cartao);
        a.setCartao(ncartao);
        a.setCep(cep);
        a.setCidade(cidade);
        a.setComplemento(complemento);
        a.setContato(contato);
        a.setCpf(cpf);
        a.setData(data);
        a.setEmail(email);
        a.setEstado(estado);
        a.setId_animal(flag);
        a.setLogradouro(logradouro);
        a.setN_cartao(flag);
        a.setNome(nome);
        a.setNumero(WIDTH);
        a.setRg(rg);
        a.setSexo(cep);
        a.setValidade(validade);
       
        cadastro.Alterar(a);
        LimparCampos();
 
    }//GEN-LAST:event_JButtonAlterarActionPerformed

    private void JButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonCancelarActionPerformed

        LimparCampos();

    }//GEN-LAST:event_JButtonCancelarActionPerformed

    private void jTextFieldemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldemailActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed

        ClienteDao cliedao = new ClienteDao();
        Cliente a = new Cliente();

        String busca = JTexFieldPesquisar.getText();
        String nome = jTextFieldNome.getText();
        String cpf = jFormattedTextFieldCpf.getText();
        String rg = jFormattedTextFieldRg.getText();
        String data = jFormattedTextFieldData.getText();
        String validade = jFormattedTextFieldValidade.getText();
        String sexo = (String) JComboBoxSexo.getSelectedItem();
        String logradouro = jTextFieldLogradouro.getText();
        String complemento = jTextFieldComplemento.getText();
        String numero = jTextFieldNumero.getText();
        String cidade = jTextFieldCidade.getText();
        String estado = (String) JComboBoxEstado.getSelectedItem();
        String cep = jFormattedTextFieldCep.getText();
        String contato = jFormattedTextFieldContato.getText();
        String email = jTextFieldemail.getText();
        String cartao = jTextFieldCartao.getText();
        String numero2 = jTextFieldIdAnimal.getText();

        a = cliedao.Buscar(busca);

        if (a != null) {
        
            jTextFieldNome.setText(a.getNome());
            jFormattedTextFieldCpf.setText(a.getCpf());
            jFormattedTextFieldRg.setText(a.getRg());
            JComboBoxSexo.setSelectedItem(a.getSexo());
            jTextFieldLogradouro.setText(a.getLogradouro());
            jTextFieldComplemento.setText(a.getComplemento());
            jTextFieldNumero.setText(a.getNumero().toString());
            jTextFieldCidade.setText(a.getCidade());
            JComboBoxEstado.setSelectedItem(a.getEstado());
            jFormattedTextFieldCep.setText(a.getCep());
            jFormattedTextFieldContato.setText(a.getContato());
            jTextFieldemail.setText(a.getEmail());
            jTextFieldCartao.setText(a.getCartao());
            jTextFieldIdAnimal.setText(a.getId_animal().toString());
            jTextFieldNCartao.setText(a.getN_cartao().toString());
            jFormattedTextFieldData.setText(a.getData());
            jFormattedTextFieldValidade.setText(a.getValidade());
        } else {
            JOptionPane.showMessageDialog(rootPane, "Cliente Não Encontrado");
        }

// TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cada_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cada_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cada_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cada_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cada_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAlterar;
    private javax.swing.JButton JButtonCancelar;
    private javax.swing.JButton JButtonNovo;
    private javax.swing.JButton JButtonSalvar;
    private javax.swing.JComboBox JComboBoxEstado;
    private javax.swing.JComboBox JComboBoxSexo;
    private javax.swing.JTextField JTexFieldPesquisar;
    private javax.swing.JLabel JlabelCliente;
    private javax.swing.JLabel Nome_Tela_Cad_Usuario;
    private javax.swing.JPanel Painel_Tela_Cad_Cliente;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldContato;
    private javax.swing.JFormattedTextField jFormattedTextFieldCpf;
    private javax.swing.JFormattedTextField jFormattedTextFieldData;
    private javax.swing.JFormattedTextField jFormattedTextFieldRg;
    private javax.swing.JFormattedTextField jFormattedTextFieldValidade;
    private javax.swing.JLabel jLabeContato;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCartao;
    private javax.swing.JLabel jLabelCep;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelComplemento;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelData;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelIdAnimal;
    private javax.swing.JLabel jLabelLogradouro;
    private javax.swing.JLabel jLabelNCartao;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelRg;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JLabel jLabelValidade;
    private javax.swing.JLabel jLabelfundo;
    private javax.swing.JLabel jLabelfundotitulo;
    private javax.swing.JTextField jTextFieldCartao;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldIdAnimal;
    private javax.swing.JTextField jTextFieldLogradouro;
    private javax.swing.JTextField jTextFieldNCartao;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldemail;
    // End of variables declaration//GEN-END:variables
}
