/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import model.Usuario;
import dao.UsuarioDao;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Kemu27
 */
public class Tela_Cad_Usuario extends javax.swing.JFrame {

    Usuario mod = new Usuario();
    UsuarioDao cadastro = new UsuarioDao();
    dao.Conectar conectar = new dao.Conectar();

   
    /**
     * Creates new form Tela_Cad_Usuario
     */
    public Tela_Cad_Usuario() {
        conectar.conexao();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Painel_Tela_Cad_Usuario = new javax.swing.JPanel();
        Matri_Tela_Cad_Usuario = new javax.swing.JLabel();
        Nome_Tela_Cad_Usuario = new javax.swing.JLabel();
        Usuário_Tela_Cad_Usuario = new javax.swing.JLabel();
        Senha_Tela_Cad_Usuario = new javax.swing.JLabel();
        JlabelTipo = new javax.swing.JLabel();
        JTexFieldMatricula = new javax.swing.JTextField();
        JTexFieldNome = new javax.swing.JTextField();
        JTexFieldUsuario = new javax.swing.JTextField();
        JTexFieldSenha = new javax.swing.JPasswordField();
        JComboBoxTipo = new javax.swing.JComboBox();
        JTexFieldPesquisar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        JButtonNovo = new javax.swing.JButton();
        JButtonSalvar = new javax.swing.JButton();
        JButtoncancelar = new javax.swing.JButton();
        JButtonAlterar2 = new javax.swing.JButton();
        jButtonBuscar = new javax.swing.JButton();
        jLabelfundo = new javax.swing.JLabel();
        Titulo_Tela_Cad_Usuario = new javax.swing.JLabel();
        jLabelfundotitulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Painel_Tela_Cad_Usuario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        Painel_Tela_Cad_Usuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Matri_Tela_Cad_Usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Matri_Tela_Cad_Usuario.setText("Matrícula");
        Painel_Tela_Cad_Usuario.add(Matri_Tela_Cad_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        Nome_Tela_Cad_Usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Nome_Tela_Cad_Usuario.setText("Nome");
        Painel_Tela_Cad_Usuario.add(Nome_Tela_Cad_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, -1));

        Usuário_Tela_Cad_Usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Usuário_Tela_Cad_Usuario.setText("Usuário");
        Painel_Tela_Cad_Usuario.add(Usuário_Tela_Cad_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 150, -1, -1));

        Senha_Tela_Cad_Usuario.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Senha_Tela_Cad_Usuario.setText("Senha");
        Painel_Tela_Cad_Usuario.add(Senha_Tela_Cad_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, -1, -1));

        JlabelTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JlabelTipo.setText("Tipo");
        Painel_Tela_Cad_Usuario.add(JlabelTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 200, -1, -1));

        JTexFieldMatricula.setEnabled(false);
        Painel_Tela_Cad_Usuario.add(JTexFieldMatricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 124, 31));

        JTexFieldNome.setEnabled(false);
        Painel_Tela_Cad_Usuario.add(JTexFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 363, 31));

        JTexFieldUsuario.setEnabled(false);
        Painel_Tela_Cad_Usuario.add(JTexFieldUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 150, 236, 31));

        JTexFieldSenha.setEnabled(false);
        Painel_Tela_Cad_Usuario.add(JTexFieldSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 290, 31));

        JComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador\t", "Usuário Padrão", " " }));
        Painel_Tela_Cad_Usuario.add(JComboBoxTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 119, 31));
        Painel_Tela_Cad_Usuario.add(JTexFieldPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 350, 31));

        jLabel1.setText("Usuário");
        Painel_Tela_Cad_Usuario.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        JButtonNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JButtonNovo.setText("Novo");
        JButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonNovoActionPerformed(evt);
            }
        });
        Painel_Tela_Cad_Usuario.add(JButtonNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 84, 33));

        JButtonSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JButtonSalvar.setText("Salvar");
        JButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonSalvarActionPerformed(evt);
            }
        });
        Painel_Tela_Cad_Usuario.add(JButtonSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 84, 33));

        JButtoncancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JButtoncancelar.setText("Cancelar");
        JButtoncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtoncancelarActionPerformed(evt);
            }
        });
        Painel_Tela_Cad_Usuario.add(JButtoncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 84, 35));

        JButtonAlterar2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JButtonAlterar2.setText("Alterar");
        JButtonAlterar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButtonAlterar2ActionPerformed(evt);
            }
        });
        Painel_Tela_Cad_Usuario.add(JButtonAlterar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 84, 35));

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });
        Painel_Tela_Cad_Usuario.add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 290, 80, 30));

        jLabelfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/user.jpg"))); // NOI18N
        Painel_Tela_Cad_Usuario.add(jLabelfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 910, 420));

        getContentPane().add(Painel_Tela_Cad_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, 936, 446));

        Titulo_Tela_Cad_Usuario.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        Titulo_Tela_Cad_Usuario.setForeground(new java.awt.Color(255, 255, 255));
        Titulo_Tela_Cad_Usuario.setText("Cadastro de Usuários");
        getContentPane().add(Titulo_Tela_Cad_Usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, -1, -1));

        jLabelfundotitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/azul.jpg"))); // NOI18N
        getContentPane().add(jLabelfundotitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 950, 60));

        setSize(new java.awt.Dimension(972, 566));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JButtoncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtoncancelarActionPerformed

          LimparCampos();
        
// TODO add your handling code here:
    }//GEN-LAST:event_JButtoncancelarActionPerformed

    private void LimparCampos() {
        JTexFieldMatricula.setText("");
        JTexFieldNome.setText("");
        JTexFieldUsuario.setText("");
        JTexFieldSenha.setText("");
        JTexFieldMatricula.setText("");
        JTexFieldPesquisar.setText("");
    }

    private void JButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonSalvarActionPerformed

        if (JTexFieldUsuario.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o Usuário para continuar");
            JTexFieldUsuario.requestFocus();

        } else if (JTexFieldSenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha a Senha para continuar");
            JTexFieldSenha.requestFocus();
        }
        mod.setNome(JTexFieldNome.getText());
        mod.setUsuario(JTexFieldUsuario.getText());
        mod.setSenha(JTexFieldSenha.getText());
        mod.setMatricula(Integer.parseInt(JTexFieldMatricula.getText()));
        mod.setTipo((String) JComboBoxTipo.getSelectedItem());

        cadastro.Salvar(mod);
        LimparCampos();

        // TODO add your handling code here:
    }//GEN-LAST:event_JButtonSalvarActionPerformed

    private void JButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonNovoActionPerformed

       
        JTexFieldMatricula.setEnabled(true);
        JTexFieldNome.setEnabled(true);
        JTexFieldUsuario.setEnabled(true);
        JTexFieldSenha.setEnabled(true);
        JTexFieldMatricula.setEnabled(true);
        JComboBoxTipo.setEnabled(true);
        LimparCampos();
        

// TODO add your handling code here:
    }//GEN-LAST:event_JButtonNovoActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed

        JTexFieldMatricula.setEnabled(false);
        JTexFieldNome.setEnabled(true);
        JTexFieldUsuario.setEnabled(true);
        JTexFieldSenha.setEnabled(true);
        JComboBoxTipo.setEnabled(true);
        JTexFieldPesquisar.setEnabled(true);

        UsuarioDao userdao = new UsuarioDao();
        Usuario a = new Usuario();

        String busca = JTexFieldPesquisar.getText();
        String nome = JTexFieldNome.getText();
        String usuario = JTexFieldUsuario.getText();
        String senha = JTexFieldSenha.getText();
        String tipo = (String) JComboBoxTipo.getSelectedItem();

        a = userdao.Buscar(busca);

        if (a != null) {
            JTexFieldNome.setText(a.getNome());
            JTexFieldUsuario.setText(a.getUsuario());
            JTexFieldMatricula.setText(a.getMatricula().toString());
            JComboBoxTipo.setSelectedItem(a.getTipo());
            JTexFieldSenha.setText(a.getSenha());

        } else {
            JOptionPane.showMessageDialog(rootPane, "Usuario Não Encontrado");
        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void JButtonAlterar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButtonAlterar2ActionPerformed
      
        JTexFieldMatricula.setEnabled(false);
        JTexFieldNome.setEnabled(true);
        JTexFieldUsuario.setEnabled(true);
        JTexFieldSenha.setEnabled(true);
        JComboBoxTipo.setEnabled(true);
        
        UsuarioDao userdao = new UsuarioDao();
        Usuario a = new Usuario();

        String nome = JTexFieldNome.getText();
        String usuario = JTexFieldUsuario.getText();
        String senha = JTexFieldSenha.getText();
        String tipo = (String) JComboBoxTipo.getSelectedItem();

       a.setNome(nome);
       a.setSenha(senha);
       a.setTipo(tipo);
       a.setUsuario(usuario);
            
       cadastro.Alterar(a);
        LimparCampos();
                   
    }//GEN-LAST:event_JButtonAlterar2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Cad_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Cad_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Cad_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Cad_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Cad_Usuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButtonAlterar2;
    private javax.swing.JButton JButtonNovo;
    private javax.swing.JButton JButtonSalvar;
    private javax.swing.JButton JButtoncancelar;
    private javax.swing.JComboBox JComboBoxTipo;
    private javax.swing.JTextField JTexFieldMatricula;
    private javax.swing.JTextField JTexFieldNome;
    private javax.swing.JTextField JTexFieldPesquisar;
    private javax.swing.JPasswordField JTexFieldSenha;
    private javax.swing.JTextField JTexFieldUsuario;
    private javax.swing.JLabel JlabelTipo;
    private javax.swing.JLabel Matri_Tela_Cad_Usuario;
    private javax.swing.JLabel Nome_Tela_Cad_Usuario;
    private javax.swing.JPanel Painel_Tela_Cad_Usuario;
    private javax.swing.JLabel Senha_Tela_Cad_Usuario;
    private javax.swing.JLabel Titulo_Tela_Cad_Usuario;
    private javax.swing.JLabel Usuário_Tela_Cad_Usuario;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelfundo;
    private javax.swing.JLabel jLabelfundotitulo;
    // End of variables declaration//GEN-END:variables
}
